name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build
      run: npm run build --if-present

    - name: Docker Build
      run: |
        docker build -t my-app:${{ github.sha }} .
        docker run --name my-app -d -p 4000:4000 my-app:${{ github.sha }}

    - name: Docker Cleanup
      run: docker stop my-app
